title: Soil Moisture Sensor
hero_image: images/banner.png
description: This introductory project uses a soil moisture probe to detect how dry the soil is and alerts the user with a warning LED. When the soil’s moisture level drops below a set threshold, the LED turns on, signaling that the plant needs watering.
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Build the soil probe
    completion:
      - engaged      
  - title: Wire the sensor circuit
  - title: Program the sensor
  - title: Add the LED indicator
  - title: Code the LED indicator
  - title: Challenge
    challenge: true
    completion:
      - external
